runtime: nodejs18
env_variables:
  SESSION_SECRET: "secret"
  INSTANCE_CONNECTION_NAME: river-sunlight-384122:asia-east1:ac-punch
  DB_USER: postgres
  DB_DATABASE: postgres
  DB_PASS: postgres
  DB_NAME: postgres
beta_settings:
  cloud_sql_instances: river-sunlight-384122:asia-east1:ac-punch